services:
  - type: web
    name: smartpixel-uz
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
